feat(Tag): Add onClick prop
dnbexperience/eufemia pull request #1183
Opened 2021-12-16 08:52 UTC by thaytharma

Adds `onClick`-prop to Tag.

I tried to use the `Button`-component for the `onClick`-version,
but that needed a lot of work around as the styling and behavior was different.

2021-12-16 10:50 UTC, langz commented
Seems like the visual tests are failing, do we need to generate new snapshots?
https://github.com/dnbexperience/eufemia/runs/4545510995?check_suite_focus=true

`yarn test:screenshots:update` - https://github.com/dnbexperience/eufemia/blob/main/package.json#L28

2021-12-16 11:04 UTC, langz requested changes
Awesome work @thaytharma 🚀

2021-12-16 11:04 UTC, langz commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
For all of this styling, is there a way to reuse what's been done in other "clickable" elements?
Like reusing mixins like `@include hover()`, `@include focus()`, `@include active()`, etc?

2021-12-16 11:04 UTC, langz commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
Something about this styling that makes it look strange in my version of Safari:
![image](https://user-images.githubusercontent.com/1359205/146360402-5f4414dd-6396-42a3-b28f-2c59fe31c748.png)

2021-12-16 11:55 UTC, thaytharma commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
Thanks for the heads-up! This has been updated 😊

2021-12-16 13:20 UTC, langz commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
https://eufemia.dnb.no/uilib/helpers/classes#sass-and-mixins

2021-12-16 13:22 UTC, langz commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
Looks great now :)

2021-12-16 13:23 UTC, langz commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
Not sure if we should reuse these mixins or do as we did here, adding our own selectors, like `&:hover`

2021-12-16 13:24 UTC, langz approved these changes

2021-12-16 21:32 UTC, tujoworker commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
If we can wait until starting of jan 22 – I would like to have a peer dev session. Basically two topics:

- Overall accessibility with tags and what semantic to use
- Try "one more time" to use the button component – it gives so much for free (like href support with correct sematnics)

2021-12-16 21:35 UTC, thaytharma commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
Sure! 😃  Let's do that @tujoworker 👍

2022-01-17 22:20 UTC, thaytharma commented on packages/dnb-eufemia/src/components/tag/style/_tag.scss
> +  &--clickable {
@tujoworker 
This PR be re-done to using `<Button variant="unstyled" ../>`. 
Can you do a re-review when you get a chance? 😊

2022-01-19 14:47 UTC, dinarosv approved these changes
Like this component a lot! 🤩  
I'm thinking we might need more information on when to use and when to not use the clickable tag, so no one puts them where a Button would be more appropriate 💭

2022-01-19 14:50 UTC, tujoworker commented
Indeed! Very good work! I will have a last check with Theyan on Friday – just to verify that my commits are ok 👍

2022-01-19 14:51 UTC, tujoworker approved these changes
Indeed! Very good work! I will have a last check with Theyan on Friday – just to verify that my commits are ok 👍

2022-01-21 10:44 UTC, merged

2022-01-26 21:21 UTC, tujoworker commented
:tada: This PR is included in version 9.19.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/9.19.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v9.19.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: