chore: es6 functions in new components
dnbexperience/eufemia pull request #1236
Opened 2022-01-31 10:43 UTC by thaytharma

This PR changes our new components to use ES6-functions. We tend to add new components based on these files, so we might apply them now if we want to keep it this way.

This might just be a personal preference, 
so please feel free to decline this PR.

2022-01-31 11:59 UTC, tujoworker requested changes
I'm fine with it. I think its good that you guys form the decision around such styles.

Could you squash the last two commits into the first one? Or you will squash it during the PR merge?

2022-01-31 12:00 UTC, tujoworker approved these changes

2022-01-31 12:09 UTC, merged

2022-01-31 12:09 UTC, thaytharma commented
> I'm fine with it. I think its good that you guys form the decision around such styles.
> 
> Could you squash the last two commits into the first one? Or you will squash it during the PR merge?

Thanks! Squashed and merged 🙌🏼

2022-01-31 12:22 UTC, dinarosv commented
I have no particular meaning about functions vs. const for components, so we can go with this 👍

2022-02-02 20:04 UTC, tujoworker commented
:tada: This PR is included in version 9.20.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/9.20.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v9.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: