docs: update oudated docs
dnbexperience/eufemia pull request #1248
Opened 2022-02-01 19:26 UTC by tujoworker

Update outdated docs

2022-02-01 20:18 UTC, langz approved these changes

2022-02-01 20:19 UTC, langz commented on packages/dnb-design-system-portal/src/docs/design-system/about.md
> +- Anders Langseth
🎊

2022-02-01 20:51 UTC, thaytharma commented on packages/dnb-design-system-portal/src/docs/design-system/about.md
> +- Anders Langseth
😍

2022-02-01 20:51 UTC, thaytharma approved these changes

2022-02-02 07:21 UTC, dinarosv commented on packages/dnb-design-system-portal/src/docs/design-system/about.md
> +- Anders Langseth
🥳  🙏  ❤️

2022-02-02 07:24 UTC, dinarosv requested changes
Thanks for updating this!

There's a section for this in Contribution as well, I will add that to this PR asap

2022-02-02 07:30 UTC, dinarosv approved these changes
Removed duplicate contributors page under Contribution guide and linked to the one you updated instead. Hope that was okay!

Please check over before merge 😊

2022-02-02 07:42 UTC, tujoworker commented
> Removed duplicate contributors page under Contribution guide and linked to the one you updated instead. Hope that was okay!
> 
> Please check over before merge 😊

Nice – very good ✨

2022-02-02 07:54 UTC, merged

2022-02-02 20:03 UTC, tujoworker commented
:tada: This PR is included in version 9.20.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/9.20.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v9.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: