Fix disabled tertiary dropdown
dnbexperience/eufemia pull request #1293
Opened 2022-02-16 12:47 UTC by AadneRo

Fix bug where the disabled dropdown of type tertiary don't have tertiary styling

Now the tertiary dropdown will look like the tertiary button when disabled

2022-02-16 13:17 UTC, tujoworker approved these changes
Awesome 🙌 Thank you so much! 

Just one thing from my side; If you either reword the git commit message by starting with `fix: ...` or make that change during the pr merge by choosing squash and give it that message prefix.

More on that topic here: https://eufemia.dnb.no/contribute/style-guides/git#commit-messages

2022-02-16 13:22 UTC, dinarosv requested changes
Nice that you fixed this so fast 😍  Just had one comment to maintain consistency in this component :)

2022-02-16 13:22 UTC, dinarosv commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
Instead of disabling this class, which have some dependencies in `_dropdown.scss`, would you consider changing the css in `dnb-dropdown-theme-ui.scss` instead? Found the applied weird border styling there :)

2022-02-16 13:23 UTC, langz approved these changes

2022-02-16 13:29 UTC, tujoworker commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
yeah, so basically use CSS to fix it, instead JavaScript. That makes sense.

2022-02-16 13:52 UTC, AadneRo commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
Removing that results in:
<img width="630" alt="Screenshot 2022-02-16 at 14 50 44" src="https://user-images.githubusercontent.com/41082005/154278597-b09f22ac-6558-416e-8f66-e31eefeb5c95.png">

2022-02-16 14:12 UTC, dinarosv commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
But also just doing this for variant tertiary of course 😊  @AadneRo

2022-02-16 14:43 UTC, tujoworker commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
@AadneRo We can have a quick chat tomorrow maybe?

2022-02-16 14:51 UTC, AadneRo commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
That would help, thank you

2022-02-17 08:34 UTC, AadneRo commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
I think I managed @tujoworker

2022-02-17 10:58 UTC, tujoworker commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
Yes! Wonderful ✨

Two more, but small things 🙏 

- run `yarn test:update dropdown`
- run `git commit --amend` and write `fix` lower case? It would else not be picked up and displayed on the [releases page](https://github.com/dnbexperience/eufemia/releases)

And tell me more about what makes you happy 😆

<img width="258" alt="Screenshot 2022-02-17 at 11 51 08" src="https://user-images.githubusercontent.com/1501870/154464959-e53b2469-e431-4464-b993-d765f96069df.png">

2022-02-17 11:29 UTC, dinarosv approved these changes
Wiiii, nice fix 🙌 ✨

2022-02-17 11:44 UTC, AadneRo commented on packages/dnb-eufemia/src/components/dropdown/Dropdown.js
> +        enableTriggerStyles && 'dnb-dropdown__trigger',
😂 I tried to import an icon first, and got frustrated when it didn't work. That led to angy-face.

Updated the commit message now, and with the test:update

2022-02-17 12:32 UTC, merged

2022-02-22 19:26 UTC, tujoworker commented
:tada: This PR is included in version 9.23.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/9.23.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v9.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: