fix(Avatar): Allow Avatar.Group to set skeleton prop
dnbexperience/eufemia pull request #1350
Opened 2022-03-10 13:57 UTC by langz

This PR just adds the property and type for skeleton to the Avatar.Group, so that it will be easier/possible to use the component with the skeleton prop. The functionality is/was already in place, take a look at https://eufemia.dnb.no/uilib/components/avatar and property skeleton to one of the demos/examples.

```
        <Avatar.Group skeleton label="label">
          <Avatar>A</Avatar>
        </Avatar.Group>
 ```

2022-03-11 08:09 UTC, langz commented on packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx
> +  skeleton?: SkeletonShow
Not sure if/how I should use this prop in the component.
As it doesn't seem like I actually need to make more code changes to be able to do:

```
<Avatar.Group skeleton label="label">
   <Avatar>A</Avatar>
</Avatar.Group>
 ```

2022-03-14 12:13 UTC, dinarosv requested changes

2022-03-14 12:13 UTC, dinarosv commented on packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx
> +  skeleton: null,
```suggestion
  skeleton: false,
```

2022-03-14 14:20 UTC, langz commented on packages/dnb-eufemia/src/components/avatar/AvatarGroup.tsx
> +  skeleton: null,
Done ✅

2022-03-14 14:27 UTC, dinarosv approved these changes

2022-03-14 19:19 UTC, langz commented
Not really sure what we've done now, when running eufemia locally, I get the following error when visiting http://localhost:8000/uilib/components/avatar/demos

```
Warning: Received `false` for a non-boolean attribute `skeleton`.
If you want to write it to the DOM, pass a string instead: skeleton="false" or skeleton={value.toString()}.
If you used to conditionally omit it with skeleton={condition && value}, pass skeleton={condition ? value : undefined} instead.
```

I'll try looking into it tomorrow.

2022-03-15 12:26 UTC, langz commented
What I wanted to achieve with this PR was the following:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1359205/158377132-b0dabeac-2beb-40ed-958d-6907c3925fd2.png">

At the moment, it's not working ,and I am not exactly sure why, but it seems to "work again", if I remove the following line https://github.com/dnbexperience/eufemia/pull/1347/commits/d2622c5022eaccc1b7e7c188e588507df4b31c7c#r826913486

2022-03-15 12:45 UTC, dinarosv commented
> At the moment, it's not working when passing skeleton to Avatar.Group, and I am not exactly sure why, but it seems to "magically work again" if I remove the following line [#1347 (comment)](https://github.com/dnbexperience/eufemia/pull/1347#discussion_r826913486)

I think you might need to pass down `skeleton` from AvatarGroup to the clone function for the Avatar? Or another option is to include it in the AvatarGroup context?

2022-03-22 09:43 UTC, langz commented
> > At the moment, it's not working when passing skeleton to Avatar.Group, and I am not exactly sure why, but it seems to "magically work again" if I remove the following line [#1347 (comment)](https://github.com/dnbexperience/eufemia/pull/1347#discussion_r826913486)
> 
> I think you might need to pass down `skeleton` from AvatarGroup to the clone function for the Avatar? Or another option is to include it in the AvatarGroup context .... edit: what if you change the order of `{skeleton: context?.skeleton}` and `avatargroupcontext` in Avatar?

Thanks, that did it 🙇 🙏

2022-03-22 10:10 UTC, merged

2022-04-05 11:34 UTC, tujoworker commented
:tada: This PR is included in version 9.25.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/9.25.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v9.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: