feat(Upload)
dnbexperience/eufemia pull request #1581
Opened 2022-09-26 12:41 UTC by AadneRo

Add Upload component mvp.

Still missing some features:
- Drag and drop to upload file

I also removed the validation, we can add validation later if needed

2022-09-26 12:55 UTC, langz commented on packages/dnb-eufemia/src/shared/locales/nb-NO.js
> +      text: 'Dra & slipp eller velg hvilke filer du vil laste opp. Filene konverteres til PDF etter opplasing',
```suggestion
      text: 'Dra & slipp eller velg hvilke filer du vil laste opp. Filene konverteres til PDF etter opplasting',
```

2022-09-26 12:58 UTC, langz commented on packages/dnb-eufemia/src/shared/Context.tsx
> +import { UploadProps } from '../components/upload/types'
```suggestion
import type { UploadProps } from '../components/upload/types'
```

2022-09-26 13:01 UTC, langz commented on packages/dnb-eufemia/src/components/upload/types.ts
> +  errorToLargeFile?: React.ReactNode
```suggestion
  errorTooLargeFile?: React.ReactNode
```

2022-09-26 13:07 UTC, langz commented on packages/dnb-eufemia/src/components/upload/types.ts
> +  uploadingLoadingText?: React.ReactNode
```suggestion
  uploadLoadingText?: React.ReactNode
```

Could/should we use the same text pattern as `uploadButtonText`?
Or is it intentional that we prefix with the word `upload` for one of the props, and `uploading` for the other one?

2022-09-26 13:10 UTC, langz commented on packages/dnb-eufemia/src/components/upload/style/_upload.scss
> +  &__loading-section {
Is this selector used? 🤔

2022-09-26 13:13 UTC, langz commented on packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx
> +    const MockCompoenent = () => {
```suggestion
    const MockComponent = () => {
```

Not anything important, just a small spelling mistake which repeats itself a few times in this file 🔤

2022-09-26 13:24 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/types.ts
> +  errorToLargeFile?: React.ReactNode
This should be removed, I'll remove it

2022-09-26 13:28 UTC, langz commented on packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx
> +  it('use the event emitter to return a file', () => {
I started looking a bit into this test, as I didn't fully understand it, but I also don't fully understand the "event emitter" thing, so it might makes sense that I don't fully grasp this.

But I do have two thoughts:
- Compared to the following test https://github.com/dnbexperience/eufemia/blob/c3e16eefca61783bf531a2af41a9ed29e50a652c/packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx#L65

2022-09-26 13:37 UTC, langz commented on packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx
> +            file: createMockFile('file.xls', 100, 'application/xls'),
```suggestion
            file: createMockFile('file.xls', 100, 'application/ppt'),
```

2022-09-26 13:40 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx
> +  it('use the event emitter to return a file', () => {
As far as I understand it the EventEmitter is a "storage box", so every time you call the useEventEmitter('shabela-shabela'), you get the same state. So in these tests I'm checking if I use the useEventEmitter correctly, that I return the {files} from the eventEmitter and that I call the {update} from the eventEmitter.

I wanted to mock the useEventEmitter, but couldn't figure out how to do it, so I replicated the behaviour in stead

2022-09-26 13:44 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/__tests__/useUpload.test.tsx
> +  it('use the event emitter to return a file', () => {
They should not have the same id though, I'll change that

2022-09-26 13:55 UTC, langz commented on packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx
> +      expect(iconElement.getAttribute('data-test-id')).toBe(
Annoys me a bit that we can't use queryByTestId here, but have to use `getAttribute('data-test-id')`.

Makes sense, since the Icon has the `data-test-id` property and not the `data-testid` property.
Could we/I, raise a PR to change https://github.com/dnbexperience/eufemia/blob/8077fdd6476e74caa461843dbd2a6779f4366050/packages/dnb-eufemia/src/components/icon/Icon.js#L364 to be `data-testid` @tujoworker ?

2022-09-26 14:08 UTC, langz commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +        icon={images[iconFileType]}
I really like this feature, displaying the icon for a given file extension 💯 

I don't want to overcomplicate things, but for instance ppt(powerpoint) probably have a lot of file extensions, like on MacBook when creating a ppt it's probably using .pptx file extension, etc.

We can probably never "support icons for all crazy variants of file extensions", but I 'm not sure where to draw the line 🖌️

2022-09-26 14:13 UTC, langz commented
Just took a quick test run of the feature, and it looks nice 👌 

Here are some screenshots/thoughts that I immediately came over when testing in Chrome on my MacBook:

- When the filename is long(so that the filename text breaks in multiple lines) the delete button looks a bit off:
<img width="750" alt="Screenshot 2022-09-26 at 16 11 58" src="https://user-images.githubusercontent.com/1359205/192298877-6c28a7e6-0bb2-414c-8057-286eeab6f4da.png">

-

2022-09-26 14:14 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/upload/properties.md
> +| `multipleFiles`                               | _(optional)_ f set true, accepting multiple files is allowed                                                                    |
```suggestion
| `multipleFiles`                               | _(optional)_ If set true, accepting multiple files is allowed                                                                    |
```

2022-09-26 14:15 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/upload/properties.md
> +| `title`                                     | _(optional)_ Custom text properties. Replace default title                                                                        |
```suggestion
| `title`                                     | _(optional)_ Custom text property. Replaces default title                                                                        |
```

I think this suggestion/pattern also could be used for the other custom text properties 🙏

2022-09-26 14:19 UTC, langz commented on packages/dnb-eufemia/src/components/upload/types.ts
> +  errorWrongFileFormat?: React.ReactNode
Doesn't look like this is used 🤔

2022-09-26 14:19 UTC, langz commented on packages/dnb-eufemia/src/components/upload/types.ts
> +  errorToLargeFile?: React.ReactNode
Good good, I believe it's the same for `errorWrongFileFormat`, it doesn't seem to be used either.

https://github.com/dnbexperience/eufemia/pull/1581/files#r980096050

2022-09-26 14:31 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/upload/demos.md
> +When uploading the file you can set the loadign state of the request using the Upload.useUpload hook and passing isLoading to the file that is being uploaded.
```suggestion
When uploading the file you can set the loading state of the request using the Upload.useUpload hook and passing isLoading to the file that is being uploaded.
```

2022-09-26 14:33 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/upload/demos.md
> +The only checks we do currently is for the file size and the file type, These errors are handled by the heml element ´input´ so they aren't selectable. If you want any other error messages you can us
```suggestion
The only checks we do currently is for the file size and the file type, These errors are handled by the HTML element ´input´ so they aren't selectable. If you want any other error messages you can use the Upload.useUpload the same way as with the loading state.
```

2022-09-26 14:58 UTC, langz commented on packages/dnb-eufemia/src/components/upload/types.ts
> +   * fileMaxSize is max size of each file in MB
Do we enforce the max file size to be the value of the prop `fileMaxSize`?
I tested setting `fileMaxSize={1}` but was still allowed to select/upload a 10MB file.

2022-09-26 18:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/upload/demos.md
> +The only checks we do currently is for the file size and the file type, These errors are handled by the heml element ´input´ so they aren't selectable. If you want any other error messages you can us
Do we enforce the max file size to be less than the value of the prop `fileMaxSize`?
I tested setting `fileMaxSize={1}` but was still allowed to select/upload a 10MB file 🤔

2022-09-27 06:55 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/style/_upload.scss
> +  &__loading-section {
removed

2022-09-27 19:07 UTC, langz commented on packages/dnb-eufemia/src/components/upload/__tests__/UploadFileListCell.test.tsx
> +      expect(iconElement.getAttribute('data-test-id')).toBe(
#1583

2022-09-28 06:39 UTC, langz commented
@AadneRo, tell me if/when you would like me to look over it again🧐👌

2022-09-28 07:54 UTC, AadneRo commented
> @AadneRo, tell me if/when you would like me to look over it again🧐👌

I'll let you know when I've updated the PR!

2022-09-28 11:10 UTC, langz commented on packages/dnb-eufemia/src/components/upload/stories/Upload.stories.tsx
> +          onFilesChange={(files: UploadFile[]) =>
```suggestion
```

I believe this can be removed now, as the prop doesn't longer exist 💯

2022-09-28 11:10 UTC, langz commented on packages/dnb-eufemia/src/shared/locales/en-GB.js
> +      text: 'Drag & drop your files or choose files to upload. Files are converted to PDF after upload.',
Just curious, how do we know that the files will be converted to PDF after the upload? 🤔 
You would think that's very dependent on what the apps/clients using this Upload component does with the files 🤔

2022-09-28 11:27 UTC, langz approved these changes
Other than the few comments I recently left, I think it looks very nice 🥇 ✅ 
Maybe @tujoworker has time to look through it once before merging it? 🙏

2022-09-28 12:05 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/Upload.tsx
> +    const addedFile = [...files, ...addedFiles]
Renamed the variable to 'newFiles'

2022-09-28 12:07 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +          data-testid="upload-exclamation-icon"
removed

2022-09-28 12:07 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +        data-testid={`upload-${iconFileType}-icon`}
removed

2022-09-28 12:09 UTC, AadneRo commented on packages/dnb-eufemia/src/shared/locales/en-GB.js
> +      text: 'Drag & drop your files or choose files to upload. Files are converted to PDF after upload.',
Do you have any insight here @tujoworker?

2022-09-28 13:52 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/Upload.tsx
> +    context.getTranslation().Upload,
Yeah, we should "require" to send in props to this function. Will make a PR.
 
From the [docs](
https://eufemia.dnb.no/contribute/getting-started/#additional-support): The function `getTranslation` will along with the properties support both `locale` and the HTML `lang` attribute. This way, these properties can be set by a component basis and a context basis.

2022-09-28 13:57 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/Upload.tsx
> +    context.getTranslation().Upload,
That said, it does not really matter for this component. In in general, its more for edge cases. Like if you would like to quickly define a different `locale` because of some unknown reason. 
That said, we do then not have TypeScript support for the locale prop 🤷‍♂️ while the `lang` prop should work, as it is a HTML Element prop.

2022-09-28 13:58 UTC, tujoworker commented on packages/dnb-eufemia/src/shared/locales/en-GB.js
> +      text: 'Drag & drop your files or choose files to upload. Files are converted to PDF after upload.',
You are right, we should remove the text. Not sure where its coming from either 💁‍♂️

2022-09-30 06:24 UTC, AadneRo commented on packages/dnb-eufemia/src/shared/locales/en-GB.js
> +      text: 'Drag & drop your files or choose files to upload. Files are converted to PDF after upload.',
I removed it

2022-09-30 07:12 UTC, langz commented on packages/dnb-eufemia/src/shared/locales/en-GB.js
> +      text: 'Drag & drop your files or choose files to upload. Files are converted to PDF after upload.',
Did we remove it, or replace it with some other default text?

2022-09-30 07:36 UTC, AadneRo commented on packages/dnb-eufemia/src/components/upload/Upload.tsx
> +    context.getTranslation().Upload,
I updated this

2022-09-30 08:55 UTC, tujoworker requested changes
✨ Very nice work Ådne! ✨ Let me know if we should sit together looking at all things next week? (Not all of my comments are that important to get in, but some 😉)

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/Upload.tsx
> +    { skeleton: context?.skeleton },
```suggestion
    { skeleton: context?.skeleton },
    context.getTranslation(props).Upload,
```

I still recommend we follow this patterns, because this way a dev and send in the `locale` or `lang` prop, and define/change (overwrite) the locale for only this component. We will add these props to the docs and the prop types. There is a task for that 👍

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/Upload.tsx
> +      <span data-testid="upload-text" className="dnb-upload__text">
```suggestion
      <P data-testid="upload-text" className="dnb-upload__text">
```

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/UploadFileInput.tsx
> +
This fine with only the button 👍

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/style/_upload.scss
> +  background: var(--color-white);
`background` is a shortcut. I recommend defining it with -color as we work with color here.

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/style/_upload.scss
> +  }
I'm curious why we need `0.75rem`.

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/types.ts
> +  errorMessage?: string | React.ReactNode
```suggestion
  errorMessage?: React.ReactNode
```

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +        <span
```suggestion
        <P
```

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +    <div
```suggestion
    <li
```

2022-09-30 08:55 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +            `dnb-upload__file-cell--${hasWarning ? '' : 'no-'}error`
```suggestion
```

Could we rather inherit the "status" from the li (cell) element? Should be fine to do with CSS. And we get less code to "maintain".

2022-10-12 13:02 UTC, tujoworker approved these changes
✨ Awesome work 🕺

2022-10-13 05:57 UTC, merged

2022-10-13 06:52 UTC, tujoworker commented on packages/dnb-eufemia/src/components/upload/UploadFileListCell.tsx
> +        icon={images[iconFileType]}
I have sent the link to your thoughts to UX Mats 👍

2022-10-19 20:22 UTC, tujoworker commented
Related PRs #1643 #1647 #1645 #1648 #1649

2022-10-23 12:02 UTC, tujoworker commented
:tada: This PR is included in version 9.33.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/9.33.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v9.33.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: