chore(TypeScript): use DatePickerProps in DatePickerProvider
dnbexperience/eufemia pull request #2089
Opened 2023-03-10 19:27 UTC by langz

2023-03-13 07:15 UTC, tujoworker requested changes

2023-03-13 07:15 UTC, tujoworker commented on packages/dnb-eufemia/src/components/date-picker/DatePicker.js
> +    console.log(this.props)
```suggestion
```

2023-03-13 07:53 UTC, langz commented on packages/dnb-eufemia/src/components/date-picker/DatePicker.js
> +    console.log(this.props)
Thanks, resolved now :)

2023-03-13 08:32 UTC, tujoworker approved these changes

2023-03-13 08:43 UTC, merged

2023-05-05 12:18 UTC, tujoworker commented
:tada: This PR is included in version 10.0.0-beta.3 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.0.0-beta.3)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.0.0-beta.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: