fix(Dialog): make action buttons responsive
dnbexperience/eufemia pull request #2373
Opened 2023-05-25 10:07 UTC by joakbjerk

## Summary

A proposal to make the action buttons inside the `Dialog` responsive. 
Not sure this is the best approach though 😄

2023-05-25 11:38 UTC, tujoworker requested changes

2023-05-25 11:38 UTC, tujoworker commented on packages/dnb-eufemia/src/components/dialog/style/dnb-dialog.scss
> +    @media screen and (max-width: 40rem) {
```suggestion
    @include allBelow(small) {
```

2023-05-25 11:38 UTC, tujoworker commented on packages/dnb-eufemia/src/components/dialog/style/dnb-dialog.scss
> +      & > .dnb-button {
We should rather remove the spacing props from the buttons I would say. Is that possible?

2023-05-25 11:44 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/dialog/style/dnb-dialog.scss
> +      & > .dnb-button {
Not sure if I'm answering your question here, but I'll give it a go 😄 
The buttons does not seem to be using the space props.

<img width="641" alt="Screenshot 2023-05-25 at 13 41 33" src="https://github.com/dnbexperience/eufemia/assets/25927156/27950563-a45e-4e27-8627-e4e65b4df902">

It looks to be set by a `> :not(:last-child)` selector instead.

Would this solution be better?
<img width="409" alt="Screenshot 2023-05-25 at 13 42 58" src="https://github.com/dnbexperience/eufemia/assets/25927156/26152bdf-66f3-4844-baa2-cb748b887a53">

2023-05-25 14:11 UTC, tujoworker commented on packages/dnb-eufemia/src/components/dialog/style/dnb-dialog.scss
> +      & > .dnb-button {
Yes, just remove all the margins and use flex row but with gap and also flex wrap.

2023-05-25 19:29 UTC, tujoworker approved these changes
Nice 👌 🙏

2023-05-26 06:35 UTC, merged

2023-05-26 08:55 UTC, tujoworker commented
:tada: This PR is included in version 10.0.0-beta.8 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.0.0-beta.8)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.0.0-beta.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: