chore: removes replaceHydrationFunction
dnbexperience/eufemia pull request #2671
Opened 2023-09-21 21:48 UTC by langz

2023-09-21 21:49 UTC, langz commented on packages/dnb-design-system-portal/gatsby-config.js
> +    DEV_SSR: true,
```suggestion
    DEV_SSR: false,
```
This is just here temporary so that others can check out this branch and run it locally, to get the same errors as I've seen.

2023-09-21 21:50 UTC, langz commented on packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
> -  getVoiceOverActiveItem(selected_sr) {
We should of course not remove this, should probably fix it.

Here's the errors this function caused in SSR:
<img width="477" alt="Screenshot 2023-09-21 at 23 23 04" src="https://github.com/dnbexperience/eufemia/assets/1359205/63620656-aa7e-4dd8-b870-681ea792172d">

2023-09-21 21:50 UTC, langz commented on packages/dnb-eufemia/src/shared/Theme.tsx
> +  const themeName = 'ui' as ThemeNames
We should of course not do this, should probably fix it some how.

Here's the errors caused in SSR when not specifying `name`:
<img width="489" alt="Screenshot 2023-09-21 at 23 25 16" src="https://github.com/dnbexperience/eufemia/assets/1359205/3fba7a9c-c7c7-46a9-abab-af69130d94a0">

2023-09-22 07:43 UTC, langz commented on packages/dnb-eufemia/src/shared/Theme.tsx
> +  const themeName = 'ui' as ThemeNames
Personally, I believe there's something happening in https://github.com/dnbexperience/gatsby-plugin-eufemia-theme-handler/blob/main/packages/gatsby-plugin-eufemia-theme-handler/themeHandler.js#L32 when SSR.
Seems like theme is `null`. Not sure how to validate this suspicion

2023-09-22 18:11 UTC, langz commented on packages/dnb-eufemia/src/shared/Theme.tsx
> +  const themeName = 'ui' as ThemeNames
I think this one will be fixed as part of https://github.com/dnbexperience/gatsby-plugin-eufemia-theme-handler/pull/6

2023-09-26 13:13 UTC, langz commented on packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
> +      // Could be solved in a better way
```suggestion
      // Could be solved in a better/different way.
```

2023-09-28 07:36 UTC, langz commented on packages/dnb-design-system-portal/package.json
> +    "gatsby-plugin-eufemia-theme-handler": "1.3.1",
Updating the version seems to result in the following issue when running `yarn start` with SSR:

```
 ERROR #98124  WEBPACK.DEVELOP-HTML

Generating development SSR bundle failed

Can't resolve '@dnb/eufemia/shared' in '/Users/anderslangseth/dev/eufemia/node_modules/gatsby-plugin-eufemia-theme-handler'

If you're trying to use a package make sure that '@dnb/eufemia/shared' is installed. If you're trying to use a local file make sure that the path is correct.

File: ../../node_modules/gatsby-plugin-eufemia-theme-handler/themeHandler.js:2:0
```

2023-09-29 14:43 UTC, tujoworker approved these changes
No more changes than that? Nice 💎

2023-10-06 07:08 UTC, tujoworker requested changes

2023-10-06 07:08 UTC, tujoworker commented on packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
> -    if (IS_MAC) {
We need a different solution there. We can simply check if the autocomplete is opened. But also add a integration test for it.

2023-10-06 07:08 UTC, tujoworker commented on packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
> -    matchOnSSR: true,
We need a integration test on this new behavior.

2023-10-18 11:06 UTC, langz commented on packages/dnb-eufemia/src/components/breadcrumb/Breadcrumb.tsx
> -    matchOnSSR: true,
This code is removed 🙏

2023-10-18 11:22 UTC, langz commented on packages/dnb-eufemia/src/components/autocomplete/Autocomplete.js
> -    if (IS_MAC) {
https://github.com/dnbexperience/eufemia/pull/2761

2023-10-18 12:44 UTC, langz commented
I do believe that "the last error" we have now is related to e2e-tests/visual tests, where we use the query param `eufemia-theme`, like https://eufemia-git-fix-removes-replace-hydration-function-eufemia.vercel.app/uilib/components/badge/demos/?data-visual-test=true&eufemia-theme=sbanken

Not sure how we want to tackle this 🤔

2023-10-18 13:40 UTC, langz commented
There seems to be an issue with the logo component in regards to ssr/hydration.
Take a look here: https://eufemia-git-fix-removes-replace-hydration-function-eufemia.vercel.app/uilib/components/logo/demos/?data-visual-test=true&eufemia-theme=sbanken

<img width="836" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/0ced5633-5cf9-4b19-93e4-568ab425f84d">

```
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sa (react-dom.production.min.js:131:278)
    at Ei (react-dom.production.min.js:293:379)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:268:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
sa @ react-dom.production.min.js:131
Ei @ react-dom.production.min.js:293
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
gs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
react-dom.production.min.js:293 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ei (react-dom.production.min.js:293:39)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at os (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```


And since the `Logo` is used in the footer, the hydration issue will happen on all pages with the footer.
Any ideas on how we could/should tackle this problem? @tujoworker 🙏

2023-10-18 13:42 UTC, tujoworker commented
Yes, its probably again the useMedia hook. We need to make a fix there!

2023-10-19 19:58 UTC, langz commented
> Yes, its probably again the useMedia hook. We need to make a fix there!

I think for this specific component Logo, the problem is that when theme is Sbanken, set through queryparam, the 1st load on SSR will result in Logo being DNB logo(because no window available and theme defaults to ui), then on clientside the Logo will of course be Sbanken. So the SVGs in the Logo differ from SSR and clientside when setting theme to Sbanken through query param.

2023-10-24 10:59 UTC, langz commented on packages/dnb-design-system-portal/src/shared/tags/CodeBlock.tsx
> +
I'll probably end up reverting or finding a better way of realizing the same as above

2023-10-24 13:38 UTC, langz commented on packages/dnb-eufemia/src/shared/VisibilityByTheme.tsx
> +    hideElem = false
⏰ TODO: I'll probably end up reverting  all of this, or finding a better way of realizing the same as above. ⏰

2023-10-24 13:38 UTC, langz commented on packages/dnb-eufemia/src/shared/__tests__/VisibilityByTheme.test.tsx
> +describe.skip('VisibilityByTheme', () => {
⏰ TODO: I'll probably end up reverting this. ⏰

2024-06-25 11:19 UTC, closed without merging