Chore(InputMasked): add support for multiple inputs
dnbexperience/eufemia pull request #2736
Opened 2023-10-09 06:49 UTC by joakbjerk

## WIP

The idea is that this addition to `InputMaksed` will remove the need for all the custom code for the `Expiry` [component](https://github.com/dnbexperience/eufemia/pull/2660) and maybe the `DatePickerInput` also.

- [ ] Come up with a better name than `SteppedMask`
- [ ] Fix styling
- [ ] Integrate `useHandleCursorPosition` hook
- [ ] Documentation(?)

2023-10-23 13:30 UTC, tujoworker commented on packages/dnb-eufemia/src/components/input-masked/InputMasked.js
> +InputMasked.Stepped = SteppedMask
We should probably not add it as a static method. I think a bundler will not be able to remove this code, if its not used. So an explicit import is probably best.

2023-11-01 12:42 UTC, tujoworker requested changes
Very nice work so far! I have some change requests. Let me know if something is unclear or you have questions.

2023-11-01 12:42 UTC, tujoworker commented on packages/dnb-eufemia/src/components/input-masked/hooks/useMultiInputValues.ts
> +    defaultValues ?? createDefaultValues()
```suggestion
    defaultValues ? defaultValues : createDefaultValues()
```

I had a case when ?? was not supported because of an outdated Storybook version in the mono-repo.
So when e.g. the DatePicker will use this, we probably should not use it as of now.

2023-11-01 12:42 UTC, tujoworker commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +  border: none;
```suggestion
@include fieldsetReset();
```

Which is a part of `utilities.scss`

2023-11-01 12:42 UTC, tujoworker commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +    float: left;
Can we avoid using float? Should be doable with flex.

2023-11-01 12:42 UTC, tujoworker commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +      color: var(--color-sea-green);
Now that this is a new "component", we should rather use CSS vars to change colors on stages.

2023-11-01 13:13 UTC, joakbjerk commented on packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/properties.mdx
> +## Multi-input mask
Yeah, that's correct 😄

2023-11-01 14:49 UTC, joakbjerk commented on packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/properties.mdx
> +### MultiInputMaskInput
Hmm, this section was suppose to describe the properties used for the `inputs` prop for `MultiInputMask` maybe change it to MultiInputMask inputs properties, if that makes sense?

2023-11-01 14:50 UTC, joakbjerk commented on packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/properties.mdx
> +| `onChange`       | _(optional)_ runs an input value changes. Has an object parameter with keys matching the id's defined in `inputs`, and values of string. E.g: `{month: string, year: string}`
Yeah that might make more sense 😄

2023-11-01 15:02 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
> +  const inputRefs = useRef<MutableRefObject<HTMLInputElement>[]>([])
Can do!

2023-11-01 15:05 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
> +  const { className, ...restOfProps } = props
Will change that 🙏

2023-11-01 15:10 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +    float: left;
Hmm, I'll look more into that, had some issues with Flexbox not working on the `legend` element. Or it might just be an firefox bug, did not check the other browsers 😅

2023-11-01 18:03 UTC, tujoworker commented on packages/dnb-design-system-portal/src/docs/uilib/components/input-masked/properties.mdx
> +### MultiInputMaskInput
Yes 👍

2023-11-02 06:37 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
> +function MultiInputMask<T extends string>({
I'll double check, but I think its needed to tell typescript that the `T` generic should be of type string, so that it can be used as an indexes for `MultiInputMaskValue` object

2023-11-02 06:45 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
> +type inputpdMaskInputProps<T extends string> = MultiInputMaskInput<T> & {
Nice catch, I noticed another type in the type declaration that I will also correct 😅

2023-11-02 06:48 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +      color: var(--color-sea-green);
Like the way it's done with the Sbanken and UI theming?

2023-11-02 07:59 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/MultiInputMask.tsx
> +function MultiInputMask<T extends string>({
It looks like its need unfortunately, to make typescript give suggestions when filling out the step ID, or onChange object properties 😕

https://github.com/dnbexperience/eufemia/assets/25927156/25761a3f-6d33-475e-aa02-f35eb8ea9432

2023-11-02 08:58 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +    float: left;
I was able to solve this by remove `float` from `legend` and setting the `fieldset` display to `display: contents`. Would that be an adequate solution, or is there a reason not to do it like that @tujoworker 🤔. I have not been able to position the legend with flexbox unfortunately. 
<img width="1344" alt="Screenshot 2023-11-02 at 09 56 18" src="https://github.com/dnbexperience/eufemia/assets/25927156/cc732d9b-6203-44e6-be0e-492492a11b98">

2023-11-02 09:04 UTC, joakbjerk commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +    float: left;
Well, looks like wrapping the `legend` content in a span, and then applying `display: contents` on the `legend` element achieves the same thing, making `flexbox` work with the `legend` element. The only issue then is the `legend.dnb-form-label` class overiding the `legends` `display` property �
<img width="1067" alt="Screenshot 2023-11-02 at 10 01 37" src="https://github.com/dnbexperience/eufemia/assets/25927156/018cef91-d7c3-4cce-ac46-c1040a991078">
�

2023-11-06 08:33 UTC, tujoworker commented on packages/dnb-eufemia/src/components/input-masked/style/dnb-input-masked.scss
> +      color: var(--color-sea-green);
yes

2023-11-06 09:50 UTC, tujoworker approved these changes
Very nice work 🥇

2023-11-06 10:56 UTC, merged

2023-11-07 21:46 UTC, tujoworker commented
:tada: This PR is included in version 10.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.12.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: