feat(PaymentCard): add styling for other card statuses
dnbexperience/eufemia pull request #2777
Opened 2023-10-23 11:14 UTC by dsa015

Add support for extra statuses: replaced, renewed and order_in_process for payment card.

Link to issue: https://github.com/dnbexperience/eufemia/issues/2776

2023-10-23 17:27 UTC, tujoworker requested changes
Nice work! Thank you 🙏

I have some suggestion regarding the import of icons.

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/payment-card/properties.mdx
> +| [Space](/uilib/components/space/properties) | _(optional)_ spacing properties like `top` or `bottom` are supported.                                                                              |
```suggestion
| [Space](/uilib/layout/space/properties) | _(optional)_ spacing properties like `top` or `bottom` are supported.                                                                              |
```

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
> +      </div>
```suggestion
      <BlockingOverlay text={translations.text_order_in_process} />
```

Looks like all tree blocks are the same, except the "text". So I suggest to make a shared component above, and consume it in each case.

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/icons/Hourglass.tsx
We should import this svg from the icon lib.

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
> +import Hourglass from './Hourglass'
```suggestion
import { hourglass as Hourglass } from '../../../icons'
```

btw. should this be a medium (24px) icon?

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
> +import CardIn from './CardIn'
```suggestion
import { card_in_medium as CardIn } from '../../../icons'
```
We should delete the `CardIn.tsx` file.

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
>  import Blocked from './Padlock'
```suggestion
import { padlock_medium as Blocked } from '../../../icons'
```
We should delete the `Padlock.tsx` file.

2023-10-23 17:27 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
>  import Expired from './Clock'
```suggestion
import { clock_medium as Expired } from '../../../icons'
```
We should delete the `Clock.tsx` file.

2023-10-24 07:18 UTC, dsa015 commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
> +import Hourglass from './Hourglass'
this hourglass icon import suggested looks fine so I will change it to use this

2023-10-24 07:19 UTC, dsa015 commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
>  import Blocked from './Padlock'
will do!

2023-10-24 07:21 UTC, dsa015 commented on packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
> +      </div>
yeah can see that its the same, will change it to make use of an component instead

2023-10-24 09:01 UTC, dsa015 commented on packages/dnb-eufemia/src/extensions/payment-card/icons/Hourglass.tsx
have updated it

2023-10-24 09:02 UTC, dsa015 commented on packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js
> +        createSkeletonClass('font', skeleton)
not sure if its correct way to implement skeleton?

2023-10-24 09:04 UTC, dsa015 commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
> +      return <Expired stroke="#fefefe"/>
since using the icon import, the default colour was black, had to specify stroke color

2023-11-01 12:51 UTC, tujoworker approved these changes
Nice work 🙏 Thank you!

Because your branch did have a different scope name (feature instead of feat) the tests do not run, so I will merge this into another branch, and then create a PR from there into main.

2023-11-01 12:51 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/payment-card/icons/index.js
> +import { hourglass as Hourglass } from '../../../icons'
```suggestion
import { clock_medium as Expired,  padlock_medium as Blocked, card_in_medium as CardIn hourglass as Hourglass } from '../../../icons'
```

Its possible to get all icons in one import.

2023-11-01 12:53 UTC, merged