feat(Section): add responsive props: breakout, outline, corderRadius, backgroundColor, textColor and innerSpace
dnbexperience/eufemia pull request #2791
Opened 2023-10-24 21:15 UTC by tujoworker

Is based on PR #2790

2023-10-27 13:44 UTC, henit requested changes

2023-10-27 13:44 UTC, langz approved these changes
Nice, that's a pretty fancy feature 👯‍♀️

2023-10-27 13:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx
> +| `breakout`                              | _(optional)_ use `true` to enable a fullscreen breakout look. Defaults to `true`.
```suggestion
| `breakout`                              | _(optional)_ use `true` to enable a fullscreen breakout look. Defaults to `true`. Supports also media query breakpoints like `{small: { top: 'medium' }}`.                                                                             |
```

2023-10-27 13:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx
> +| `outline`                               | _(optional)_ define a custom border color. If `true` is given, `color-black-8` is used. Use a Eufemia color.
```suggestion
| `outline`                               | _(optional)_ define a custom border color. If `true` is given, `color-black-8` is used. Use a Eufemia color. Supports also media query breakpoints like `{small: { top: 'medium' }}`.                                                   |
```

2023-10-27 13:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx
> +| `roundedCorner`                         | _(optional)_ use `true` to enable rounded corners (border-radius). Defaults to `false`.
```suggestion
| `roundedCorner`                         | _(optional)_ use `true` to enable rounded corners (border-radius). Defaults to `false`.  Supports also media query breakpoints like `{small: { top: 'medium' }}`.                                                                       |
```

2023-10-27 13:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx
> +| `backgroundColor`                       | _(optional)_ define a custom background color, instead of a variant. Use a Eufemia color.
```suggestion
| `backgroundColor`                       | _(optional)_ define a custom background color, instead of a variant. Use a Eufemia color. Supports also media query breakpoints like `{small: { top: 'medium' }}`.                                                                      |
```

2023-10-27 13:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx
> +| `textColor`                             | _(optional)_ define a custom text color to compliment the backgroundColor. Use a Eufemia color.
```suggestion
| `textColor`                             | _(optional)_ define a custom text color to compliment the backgroundColor. Use a Eufemia color. Supports also media query breakpoints like `{small: { top: 'medium' }}`.                                                                |
```

2023-10-27 13:44 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/components/section/properties.mdx
> +| `outline`                               | _(optional)_ define a custom border color. If `true` is given, `color-black-8` is used. Use a Eufemia color.
What's an eufemia color? Could we provide a link to the docs of available eufemia colors? Or list them here?

2023-10-27 13:44 UTC, langz commented on packages/dnb-eufemia/src/components/section/Section.tsx
> +  outline?: OutlineColor | SectionMedia<OutlineColor>
Do we have a type for "Eufemia colors" that we could use here? Like a type that lists out all "eufemia colors"? 
Or maybe it's just overcomplicating things to add this 🤔

2023-10-30 20:04 UTC, tujoworker commented on packages/dnb-eufemia/src/components/section/Section.tsx
> +  outline?: OutlineColor | SectionMedia<OutlineColor>
Yeah, we don't have that today. Could be interesting. But a huge color naming update will hit us soon. So we need to wait.

2023-10-31 08:29 UTC, henit approved these changes

2023-11-01 20:01 UTC, merged

2023-11-03 07:18 UTC, tujoworker commented
:tada: This PR is included in version 10.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.11.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: