fix(PhoneNumber): return country code only when a number is given
dnbexperience/eufemia pull request #2920
Opened 2023-11-20 19:53 UTC by tujoworker

2023-11-27 12:16 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/stories/PhoneNumber.stories.tsx
> +      // validateInitially
//?

2023-11-27 12:21 UTC, henit requested changes

2023-11-27 12:21 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +      if (lang === langRef.current) {
Since `lang` is not in the memo dependencies array, won't this lead to the memo not being re-called if `lang` is changed?

2023-11-27 12:21 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +  const onFocusHandler = ({ updateData }) => {
Any good reason not to `useCallback` this one?

2023-11-27 12:21 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/stories/PhoneNumber.stories.tsx
> +      // validateInitially
Actually, Storybook in Eufemia is used as a place for drafting and does not need to be that height quality.

2023-11-27 12:24 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +      if (lang === langRef.current) {
This is only used for the first render. When lang changes, there is a new check we. 
This is because we only process the first/needed country. But later we process all.

2023-11-27 12:24 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +  const onFocusHandler = ({ updateData }) => {
No, we can add it 👍

2023-11-27 12:25 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +      if (lang === langRef.current) {
Not just not being recalled, but actually having the old value even if it was changed before memo is recalled because `value` was changed.... Which practically means that if will never run true?

2023-11-27 12:26 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +      if (lang === langRef.current) {
ignoring the exhausive-deps rule is risky 😅

2023-11-27 13:36 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +      if (lang === langRef.current) {
It looks like we can remove that change 👍

2023-11-27 17:00 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +  const onFocusHandler = ({ updateData }) => {
Done

2023-11-27 17:01 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +      if (lang === langRef.current) {
Also added deps ✅

2023-11-28 07:53 UTC, langz approved these changes
Looks very good to me.
Should we add a few lines to the docs, describing this functionality, perhaps in the info or events section? 🙏

2023-11-29 07:45 UTC, henit requested changes

2023-11-29 07:45 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +  useMemo(() => {
If the hook is not returning anything, I would suggest using `useEffect` instead of `useMemo`. Another reason for using effect instead, is that a useMemo is running in the middle of the render process, and if you change the `dataRef` then, it might have consequences (now or in the future) for logic that is part of the render process and depend on that ref, when the logic of the render running before this hook has one value in the ref, while after it is another one. A `useEffect` runs after the render, and triggers a re-render if needed, which is less likely to cause issues like the described cases.

2023-11-29 07:45 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +    if (lang !== langRef.current) {
I see that `langRef` is set to the initial value when calling `useRef(lang)`, then used in this if and nowhere else. If I understand the flow correctly, the `dataRef` need to be updated every time lang changes. This will not happen correctly now if I understand the current logic. The initial value of the `lang` prop will be put in the ref at first render, then the ref is never updated (as far as I can see). So if the `lang` change to something other than what it was initially, it will trigger this change in `dataRef`. However, if it is changed back to the original value it was during the first render, `lang` will not be !== `langRef.current` (since the ref was never updated after initial rende), so then the `dataRef` would remain what it was from the previous lang....

2023-11-29 07:45 UTC, henit commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +    if (lang !== langRef.current) {
The new value recieved by the `useRef` call itself will not update the ref, hence doc: https://react.dev/reference/react/useRef#parameters

2023-11-29 07:50 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +  useMemo(() => {
yeah, but in this case, we want the change in sync. We have just refs here, and can't trigger a re-render via state update.

2023-11-29 08:13 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +    if (lang !== langRef.current) {
Yes, added a new commit to make it possible to switch locales multiple times. Thanks for finding this issue 🙏

2023-11-29 09:46 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +  useMemo(() => {
Nice, we still could enhance the code readability with your feedback. Thanks 🙏

2023-11-29 10:06 UTC, henit approved these changes

2023-11-29 13:19 UTC, merged

2023-12-12 11:53 UTC, tujoworker commented
:tada: This PR is included in version 10.15.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.15.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: