chore(useDataValue): Add internal `updateValue`
dnbexperience/eufemia pull request #2923
Opened 2023-11-21 11:16 UTC by tujoworker

2023-11-21 13:58 UTC, langz approved these changes

2023-11-21 14:32 UTC, henit requested changes

2023-11-22 08:01 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
> -      onChange?.(newValue)
The only motivation with updateValue is to "not" call onChange during a state change from outside. But it does work technically. onChange should be tied to a user event I would argument.

2023-11-22 08:05 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/hooks/useDataValue.ts
> -      onChange?.(newValue)
`changedRef` is used for a focus event handling. I'm not sure if this should be set to true i this case. What do you think?

2023-11-22 12:52 UTC, tujoworker commented
Had a call with @henit and this are looking good 👍

2023-11-22 13:39 UTC, merged

2023-12-12 11:54 UTC, tujoworker commented
:tada: This PR is included in version 10.15.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.15.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: