fix(forms): update data context with initially given value
dnbexperience/eufemia pull request #3135
Opened 2023-12-20 15:20 UTC by tujoworker

Reprod: https://codesandbox.io/p/sandbox/eufemia-starter-forked-j5l7ct?file=%2Fsrc%2FApp.tsx%3A34%2C1

Fixes #3079

2023-12-21 11:40 UTC, langz approved these changes

2023-12-21 11:40 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
> +- `continuousValidation` in order to validate without without a focus event beforehand. Should only be used for testing purposes.
Is it correct that all of the props above(`validateInitially`, `validateUnchanged`, and `continuousValidation`) is only for testing purposes? Can it never be used in a real life scenario? 🤔

2023-12-21 11:40 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
> +- `error` error object like `FormError` that includes the string to display or an object with the key `validationRule`. More info down below.
```suggestion
- `error` object like `FormError` that includes the string to display or an object with the key `validationRule`. More info down below.
```

2023-12-21 11:40 UTC, langz commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
> +1. `required` prop
👍

2023-12-21 11:47 UTC, langz commented
I tried testing the [reprod](https://codesandbox.io/p/sandbox/eufemia-starter-forked-j5l7ct?file=%2Fsrc%2FApp.tsx%3A34%2C1) you posted, but I think it was using the wrong eufemia source.
So I created a [reprod](https://codesandbox.io/p/sandbox/eufemia-starter-forked-kzpdh4?file=%2Fsrc%2FApp.tsx%3A34%2C1), and it seems to work great.

2023-12-21 11:49 UTC, langz requested changes
I tried testing the [reprod](https://codesandbox.io/p/sandbox/eufemia-starter-forked-j5l7ct?file=%2Fsrc%2FApp.tsx%3A34%2C1) you posted, but I wouldn't say that it works as intended? 🤔 

The `onSubmit` event still returns `undefined`, as reported in https://github.com/dnbexperience/eufemia/issues/3079

I've also come up with one other example/variant that we perhaps should support, and that's when some data is set through `value` in the Component's prop, and other values are set through Form.Handlers `data` prop.
Let's say in the [following CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-r55zs7?file=%2Fsrc%2FApp.tsx%3A37%2C1).
Should we merge these together and return in the onSubmit event?


And to further complicate things, if we set `a` to value `x` through data prop of `Form.Handler`, and in the `Field` with path `/a` we set `value="y"` and press `onSubmit`, will we return `{a: "x"}` or `{a:"y"}`? Who overwrites who
 🤔

2023-12-21 19:23 UTC, tujoworker commented
Very good feedback and very true.

I think the value "near" the component should win. Also, in some cases it may make sense to make "one" component controlled (with a local state), and then it's even more logical that the value should be prioritized, I would say. 

I will make a change in the PR regarding that 👍

2023-12-21 20:50 UTC, tujoworker commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
> +- `continuousValidation` in order to validate without without a focus event beforehand. Should only be used for testing purposes.
Yeah, we may find a better formulation 🤔

2023-12-22 08:47 UTC, tujoworker commented
I'v made change. Can you check if it works as expected? Also, we need to get in the PR build version in [this CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-j5l7ct).

2023-12-22 09:32 UTC, langz commented
> I'v made change. Can you check if it works as expected? Also, we need to get in the PR build version in [this CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-j5l7ct).

Great work, thanks.

I've updated the following two CSBs, using the build from this PR, now:
- https://codesandbox.io/p/sandbox/eufemia-starter-forked-r55zs7 (example where we use both data and value)
- https://codesandbox.io/p/sandbox/eufemia-starter-forked-j5l7ct (example where we only use value)

2024-01-02 12:25 UTC, tujoworker commented
Nice findings! Thank you.

I added some tests with `StrictMode` and they did fail the same way as in the CSB.
Also, I [added fix](https://github.com/dnbexperience/eufemia/pull/3135/files#diff-286fe1bc4c98747f348b6f9ffba318ab1ceac84fe7054969fbc381b3a00acc77R293) so it works in `StrictMode` too.

2024-01-02 13:34 UTC, joakbjerk approved these changes
Nice! Seems to be working as intended now 😄

2024-01-02 13:34 UTC, joakbjerk commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/create-component.mdx
> +- `continuousValidation` in order to validate without without a focus event beforehand. Used for rare cases.
Not sure if you actually need to fix this typo, as it seems to be the same typo as fixed [here](https://github.com/dnbexperience/eufemia/pull/3158/commits/5c8f89d88aff843bd398a949eb35f8fea02f136a) 🤔

```suggestion
- `continuousValidation` in order to validate without a focus event beforehand. Used for rare cases.
```

2024-01-02 15:10 UTC, merged

2024-01-04 20:52 UTC, tujoworker commented
:tada: This PR is included in version 10.16.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.16.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: