fix(Field.PhoneNumber): make country code only search for country name based on chosen locale
dnbexperience/eufemia pull request #3156
Opened 2023-12-29 08:12 UTC by joakbjerk

solves: https://github.com/dnbexperience/eufemia/issues/3052

2023-12-30 09:43 UTC, tujoworker requested changes

2023-12-30 09:43 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/PhoneNumber.tsx
> +    search_content: [content],
```suggestion
```

Because it's the same as the content.

2023-12-30 09:43 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
> +  it('should show search results based on locale', async () => {
I think we already have such a test. And it may need adjustments.

2024-01-02 07:29 UTC, joakbjerk commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
> +  it('should show search results based on locale', async () => {
I might be wrong, but I cant find any other tests for this 😶

2024-01-02 12:41 UTC, tujoworker approved these changes
Nice! Thank you!

2024-01-02 12:41 UTC, tujoworker commented on packages/dnb-eufemia/src/extensions/forms/Field/PhoneNumber/__tests__/PhoneNumber.test.tsx
> +  it('should show search results based on locale', async () => {
Yes! Agreed! I've moved both tests to their 
own `describe` block.

2024-01-02 13:27 UTC, merged

2024-01-04 20:52 UTC, tujoworker commented
:tada: This PR is included in version 10.16.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.16.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: