fix(Form.Handler): ensure timeout executes always
dnbexperience/eufemia pull request #3405
Opened 2024-03-22 11:56 UTC by tujoworker

2024-03-22 13:08 UTC, joakbjerk requested changes

2024-03-22 13:08 UTC, joakbjerk commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/Handler/info.mdx
> +The `Form.Handler` component provides both the [Form.Element](/uilib/extensions/forms/extended-features/Form/Element/info/) and a HTML form element.
This link is dead now 🪦

2024-03-22 19:26 UTC, tujoworker commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/Handler/info.mdx
> +The `Form.Handler` component provides both the [Form.Element](/uilib/extensions/forms/extended-features/Form/Element/info/) and a HTML form element.
Almost yeah. The heading is missing. We can create a one-pager instead. I just don't think we need to list `Form.Element` as a thing devs need to use/know off.

2024-03-25 08:43 UTC, joakbjerk approved these changes
Looking good 👑

2024-03-25 08:43 UTC, joakbjerk commented on packages/dnb-design-system-portal/src/docs/uilib/extensions/forms/extended-features/Form/Handler/demos.mdx
> +- You can starting wiring, wait a second or two and remove the whole text again and blur the field. The async validation return will be omitted and the "required" error message will be shown.
```suggestion
- You can start writing, wait a second or two and remove the whole text again and blur the field. The async validation return will be omitted and the "required" error message will be shown.
```

2024-03-25 11:02 UTC, merged

2024-03-25 13:05 UTC, tujoworker commented
:tada: This PR is included in version 10.25.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.25.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: