feat(Field.Date): add DatePickerProps (WIP)
dnbexperience/eufemia pull request #4160
Opened 2024-10-21 12:48 UTC by joakbjerk

## WIP

- [ ] Look for other possible solutions to forward DatePickerProps
- [ ] Look for other solutions for typing props

2024-11-08 14:24 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
> +    // Current solution is solvede this way, as the ToCamelCase type does not does not retain the JSDOC comments,
```suggestion
    // Current solution is solved this way, as the ToCamelCase type does not does not retain the JSDOC comments,
```

2024-11-08 14:27 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
> +    showInput?: boolean
```suggestion
    showInput?: DatePickerProps['show_input']
```
?

2024-11-08 14:28 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
> +    opened?: boolean
```suggestion
    opened?: DatePickerProps['opened']
```
?

2024-11-08 14:30 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +    doc: 'If set to `true`, a cancel button will be shown. You can change the default text by using `cancel_button_text="Avbryt"` Defaults to `false`. If the `range` property is `true`, then the canc
Doesn't this default to true?

Here's from the code:
`showCancelButton = true`

2024-11-08 14:31 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +    doc: 'If set to `true`, a reset button will be shown. You can change the default text by using `reset_button_text="Tilbakestill"` Defaults to `false`.',
Doesn't this default to true?

Here's from the code:
`showResetButton = true`

2024-11-08 14:32 UTC, joakbjerk commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +    doc: 'If set to `true`, a cancel button will be shown. You can change the default text by using `cancel_button_text="Avbryt"` Defaults to `false`. If the `range` property is `true`, then the canc
Yeah thats true in this case. Copy paste syndrom 😄

2024-11-08 14:32 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +    doc: 'If the input fields with the mask should be visible. Defaults to `false`.',
Doesn't this default to true, and not false?

Here's from the code:
`showInput = true`

2024-11-08 14:41 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
> +     * If the input fields with the mask should be visible. Defaults to `false`.
```suggestion
     * If the input fields with the mask should be visible. Defaults to `true`.
```

2024-11-08 14:41 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
> +     * If set to `true`, a reset button will be shown. You can change the default text by using `reset_button_text="Tilbakestill"` Defaults to `false`.
```suggestion
     * If set to `true`, a reset button will be shown. You can change the default text by using `reset_button_text="Tilbakestill"` Defaults to `true`.
```

2024-11-08 14:42 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/Date.tsx
> +     * If set to `true`, a cancel button will be shown. You can change the default text by using `cancel_button_text="Avbryt"` Defaults to `false`. If the `range` prop is `true`, then the cancel butt
```suggestion
     * If set to `true`, a cancel button will be shown. You can change the default text by using `cancel_button_text="Avbryt"` Defaults to `true`. If the `range` prop is `true`, then the cancel button is shown.
```

2024-11-08 14:48 UTC, langz approved these changes
Looks good :) 

I've:
- Tested it in the deploy preview
- Changed a bit in docs and comments regarding default values for 3-4 fields.
- Added entry in the forms changelog for v10.55.0 https://github.com/dnbexperience/eufemia/pull/4220

@tujoworker can also take a look at it, if he finds time.
After this I think it's smart to finally release v10.55.0 😅

2024-11-08 15:06 UTC, langz requested changes
After rebasing with `main` branch, a few `Field.Date` tests broke 🤔 
Filling the console with:
`Eufemia convertStringToDate got invalid date: undefined`

Could it be related to this https://github.com/dnbexperience/eufemia/pull/2799 coming into play?

2024-11-08 17:57 UTC, joakbjerk commented
> After rebasing with `main` branch, a few `Field.Date` tests broke 🤔 
> Filling the console with:
> `Eufemia convertStringToDate got invalid date: undefined`
> 
> Could it be related to this https://github.com/dnbexperience/eufemia/pull/2799 coming into play?

Seems to be issues stemming from the rewrite itself. I'll fix and add tests for those cases on monday 🙏

2024-11-15 12:47 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +// Filter out properties that are handeled by `useFieldProps` or has a different default value
```suggestion
// Filter out properties that are handled by `useFieldProps` or has a different default value
```

2024-11-15 12:47 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +// Filter out the events that are handeled by `useFieldProps`
```suggestion
// Filter out the events that are handled by `useFieldProps`
```

2024-11-15 12:49 UTC, langz commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +// Since they require `Field.Date` specific comments, due to them having different default values
```suggestion
// Since they require `Field.Date` specific comments?, due to them having different default values
```
comments?

2024-11-15 12:53 UTC, joakbjerk commented on packages/dnb-eufemia/src/extensions/forms/Field/Date/DateDocs.ts
> +// Since they require `Field.Date` specific comments, due to them having different default values
changed to documentation 🙏

2024-11-15 12:59 UTC, langz approved these changes
Nice nice 👏 

I'm not 100% sure why we've needed to make changes in `DatePicker` though 🤔

2024-11-15 13:04 UTC, joakbjerk commented
> Nice nice 👏
> 
> I'm not 100% sure why we've needed to make changes in `DatePicker` though 🤔

Just to make it easier to filter out props that we don't want to be used as `html` `attributes` for the span element that wraps all the DatePicker related components. I got a couple of "X is not a valid html attributes, write it in lower case if you want to use it as such"-error messages. 

And it also removes the weird bracket encapsulation around the block of code where the attributes gets re-assigned to the `restProps`. Also removes the need for the `attributes` to be a `let`, just so we could re-assign the `attributes` variable inside the bracket encapsulation.

2024-11-17 22:31 UTC, langz commented on packages/dnb-eufemia/src/shared/locales/index.ts
> -export type TranslationsEnUS = (typeof locales)['en-US']
Are these changes intentional and needed?

2024-11-17 22:33 UTC, langz commented on packages/dnb-eufemia/src/shared/locales/index.ts
> -export type TranslationsEnUS = (typeof locales)['en-US']
I assume not, and will revert this.

2024-11-17 22:37 UTC, langz commented on packages/dnb-eufemia/src/shared/locales/index.ts
> -export type TranslationsEnUS = (typeof locales)['en-US']
But when I did so, multiple tests fail 😢

2024-11-18 06:12 UTC, joakbjerk commented
> I've:
> - [Solved merge conflict towards main](https://github.com/dnbexperience/eufemia/pull/4160/commits/8a759a70dcae4ce0bba78292f82f38feae5b7532)
> - [Ran Prettier](https://github.com/dnbexperience/eufemia/pull/4160/commits/8a759a70dcae4ce0bba78292f82f38feae5b7532)
> - [Reverted removal of en-us locale](https://github.com/dnbexperience/eufemia/pull/4160/commits/0b1dfff428309b3cd0333d0c0725e0fd317709b2)
> 
> After reverting the removal of en-us locale, tests starts failing 😢 

The en-us was added in the camelCase pr, but then i noticed that we dont document it as being exported by default in the translation object, so I removed it in this pr since it fucks up all the tests involving the datepicker input, that runs after the us locale test for Field.Date. so by removing it, the translation object reverts to how it was before the camelCase pr

2024-11-18 06:43 UTC, langz commented
> > I've:
> > 
> > * [Solved merge conflict towards main](https://github.com/dnbexperience/eufemia/pull/4160/commits/8a759a70dcae4ce0bba78292f82f38feae5b7532)
> > * [Ran Prettier](https://github.com/dnbexperience/eufemia/pull/4160/commits/8a759a70dcae4ce0bba78292f82f38feae5b7532)
> > * [Reverted removal of en-us locale](https://github.com/dnbexperience/eufemia/pull/4160/commits/0b1dfff428309b3cd0333d0c0725e0fd317709b2)
> > 
> > After reverting the removal of en-us locale, tests starts failing 😢
> 
> The en-us was added in the camelCase pr, but then i noticed that we dont document it as being exported by default in the translation object, so I removed it in this pr since it fucks up all the tests involving the datepicker input, that runs after the us locale test for Field.Date. so by removing it, the translation object reverts to how it was before the camelCase pr

Ok ok, thanks :) 
A bit difficult for me to understand that that change could be related to this feature.
I've once again removed ed-us locale https://github.com/dnbexperience/eufemia/pull/4160/commits/d188d66659571286c83264d1e08141f0feab527d

2024-11-18 06:44 UTC, merged

2024-11-18 07:11 UTC, tujoworker commented
:tada: This PR is included in version 10.56.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dnb/eufemia/v/10.56.0)
- [GitHub release](https://github.com/dnbexperience/eufemia/releases/tag/v10.56.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-11-18 07:28 UTC, joakbjerk commented
> > > I've:
> > > 
> > > * [Solved merge conflict towards main](https://github.com/dnbexperience/eufemia/pull/4160/commits/8a759a70dcae4ce0bba78292f82f38feae5b7532)
> > > * [Ran Prettier](https://github.com/dnbexperience/eufemia/pull/4160/commits/8a759a70dcae4ce0bba78292f82f38feae5b7532)
> > > * [Reverted removal of en-us locale](https://github.com/dnbexperience/eufemia/pull/4160/commits/0b1dfff428309b3cd0333d0c0725e0fd317709b2)
> > > 
> > > After reverting the removal of en-us locale, tests starts failing 😢
> > 
> > 
> > The en-us was added in the camelCase pr, but then i noticed that we dont document it as being exported by default in the translation object, so I removed it in this pr since it fucks up all the tests involving the datepicker input, that runs after the us locale test for Field.Date. so by removing it, the translation object reverts to how it was before the camelCase pr
> 
> Ok ok, thanks :) A bit difficult for me to understand that that change could be related to this feature. I've once again removed en-us locale [d188d66](https://github.com/dnbexperience/eufemia/commit/d188d66659571286c83264d1e08141f0feab527d)
> 
> is this something we should follow-up @joakbjerk? Or is it fine as it is now?

I think it's fine as it is now @langz 🤔